numericIdentifier and textIdentifier passed to the audit log message
DFE-Digital/login.dfe.services pull request #419
Opened 2022-09-23 10:35 UTC by rashthedude

Passing the `numericIdentifier` and `textIdentifier` to the audit log when a user is deleted from an organisation.

2022-09-23 15:14 UTC, malikimran34 commented on src/app/users/removeOrganisationAccess.js
> +      numericIdentifier (${numericIdentifier}) and textIdentifier (${textIdentifier})`,
make audit logs readable

2022-09-23 15:14 UTC, malikimran34 commented on src/app/users/removeOrganisationAccess.js
> +  const textIdentifier = getAllUserDetails.organisations[0]['textIdentifier'];
does we audit single or multiple org identifier?

2022-09-23 15:14 UTC, malikimran34 commented on package.json
> +    "login.dfe.dao": "2.6.4",
please give ^ a try then npm install

2022-09-26 14:32 UTC, malikimran34 commented on src/app/users/removeOrganisationAccess.js
> +      numeric Identifier and textIdentifier(${JSON.stringify(numericIdentifierAndtextIdentifier)})`,
typo in textIdentifier it should be 'text identifier'

2022-09-26 14:35 UTC, malikimran34 requested changes
can you include the package json and also i am looking into audit database i cannot find any entry just to make sure its logging in the audit table. Thanks

2022-10-04 12:11 UTC, rashthedude commented
@malikimran34 I have replaced the audit transporter package which was throwing up errors with Sequelize transport, which seems to be working correctly.

2022-11-15 10:32 UTC, ipredoi reviewed
Please check and update the unit tests related to this change in `test/unit/app/users/postRemoveOrganisation.test.js`

2022-11-15 12:19 UTC, ipredoi approved these changes

2022-11-15 13:38 UTC, malikimran34 approved these changes

2022-11-15 13:38 UTC, merged